### ISSUE TITLE
Push tags to release

### ISSUE THREAD

**Issue by sebdeckers** [vitalk/ansible-secure-ssh#8]
Hi @vitalk Thank you for this very useful role.

Installing this role via ansible-galaxy only installs the most recent tag (0.2.1).

Could you please tag the latest commit and push the tags to GitHub?

Thanks!

**Comment by vitalk** [comment]
Hi @sebdeckers!

Thank for your feedback. I published a new release and pushed new tag (https://github.com/vitalk/ansible-secure-ssh/releases/tag/0.3.0).

**Comment by sebdeckers** [comment]
Thank you for the help. I was actually interested in a tag for the more recent patches on `master` branch. They fix a deprecation warning in recent Ansible releases.

See:
https://github.com/vitalk/ansible-secure-ssh/compare/0.3.0...master

But I also [learned](https://www.jeffgeerling.com/blog/2017/patching-or-using-forked-version-ansible-galaxy-role) how to do it manually in my `requirements.yml` file:

```yaml
- name: vitalk.secure-ssh
  version: master
  src: https://github.com/vitalk/ansible-secure-ssh
```
